### ISSUE TITLE
Knerser-Ney Smoothing formula 6.23

### ISSUE THREAD

**Issue by ytdu** [jacobeisenstein/gt-nlp-class#35]
It seems like the formula 6.23 does not agree with what [wikipedia](https://en.wikipedia.org/wiki/Kneser%E2%80%93Ney_smoothing) gives.

I find the probability sum less than 1 according to the formula in the note.
Correct me if I'm wrong.
Thanks.

**Comment by ytdu** [comment]
I also recommend Good-Turing smoothing to be included in the notes.

**Comment by ytdu** [comment]
Hi, thank you for your kind reply. Here is what I think.

According to Formula 6.23 and 6.25:
![image](https://user-images.githubusercontent.com/7380587/43448858-8a656edc-94e1-11e8-85b9-eb1a86b96071.png)

![image](https://user-images.githubusercontent.com/7380587/43448834-7da5ca84-94e1-11e8-8302-b9f4f3ad6d6a.png)

Formula 6.23 is normalized iff the sum over Formula 6.24 is 1.

It seems that only the P_continuation of unseen words are sumed, while the denominator in 6.24 is over all words.
![image](https://user-images.githubusercontent.com/7380587/43449074-1cf10ca2-94e2-11e8-8574-21c94ab176ac.png)

I refered to the survey you sent me. The formula in it is like:
![image](https://user-images.githubusercontent.com/7380587/43449373-d94eb322-94e2-11e8-95db-9bf876b9690e.png)
The gamma is a normalization term, as opposed to the discounted probability as in Formula 6.25. I think that is a big difference.


  By the way, I find two words confusing in the paragraph between Formula 6.24 and 6.25:
![image](https://user-images.githubusercontent.com/7380587/43449149-517b2548-94e2-11e8-80a4-fa0bb63e3df7.png)
![image](https://user-images.githubusercontent.com/7380587/43449161-55ffd186-94e2-11e8-96d6-bacdf43a7e49.png)

Thanks.

**Comment by jacobeisenstein** [comment]
Many apologies for the long delay. I was focusing on improving other aspects of the text -- in other words, lazily procrastinating on examining this carefully :) I think you are absolutely correct. Because this isn't a critical detail, I'm going to follow the survey's example and simply describe alpha(u) as a normalization term. I've also changed the text to hopefully address the other confusing point that you mention. Thanks for your careful attention to this!
